### ISSUE TITLE
Allow `mask` argument in network_device module as a string and convert in the module

### ISSUE THREAD

**Issue by jeffkala** [CiscoISE/ansible-ise#109]
**Prerequisites**
* [x] Have you tested the operation in the API directly? yes
* [x] Do you have the latest ISE Collection version? yes
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue. yes

**Describe the bug**

With how ansible with jinja2 variable substitution works requiring the `mask` argument to be an integer requires users to get overly created to type cast a string into an integer which isn't really natively supported in jinja2.  As even using `{{ my_mask | int }}` results in a string with the way jinja2 rendering works.

**Expected behavior**

This is something that is almost always covered with the actual module where the original module_arg spec can accept a string and the modules python logic before the API call via SDK can handle the str -> int casting.

**Screenshots**
n/a

example snippet of the playbook that DOESN'T work:
```yml
    - name: "3030 - CREATE NEW ISE DEVICE OBJECT"
      cisco.ise.network_device:
         ise_username: "{{ ise_svc_user }}"
         ise_password: "{{ ise_svc_pwd }}"
         ise_hostname: "{{ ise_instance }}"
         ise_verify: false
         ise_debug: true
         ise_uses_api_gateway: false
         state: present
        ...omitted...
         NetworkDeviceIPList:
           ipaddress: "{{ primary_ip4.host }}"
           mask: "{{ primary_ip4.mask_length | int }}"
```

One of the very few workaround that will work: Essentially manually create a dictionary
```yml
    - name: "3030 - CREATE NEW ISE DEVICE OBJECT"
      cisco.ise.network_device:
         ise_username: "{{ ise_svc_user }}"
         ise_password: "{{ ise_svc_pwd }}"
         ise_hostname: "{{ ise_instance }}"
         ise_verify: false
         ise_debug: true
         ise_uses_api_gateway: false
         state: present
        ...omitted...
         NetworkDeviceIPList:
           - "{{ {'ipaddress': primary_ip4.host} | ansible.builtin.combine({'mask': primary_ip4.mask_length}) }}"
```
Error:
```
Request
        URL: https://10.36.126.153:9060/ers/config/networkdevice/name/jeff-test2
        Method: GET
        Headers:
                User-Agent: python-requests/2.28.0
                Accept-Encoding: gzip, deflate
                Accept: application/json
                Connection: keep-alive
                authorization: Basic c3ZjLW5hdXRvYm90LWlzZTprWEwtZ24+RitNbnM1cjdpP14+YnNCVg==
                Content-type: application/json;charset=utf-8
        Params:
              {}

Response
        Status: 404 -
        Headers:
                Cache-Control: no-cache, no-store, must-revalidate
                Expires: Thu, 01 Jan 1970 00:00:00 GMT
                Set-Cookie: JSESSIONIDSSO=B6FD632273489401E53FF508AA4F15CB; Path=/; Secure; HttpOnly, APPSESSIONID=69D633CA12A78F668FD82625496F83F2; Path=/ers; Secure; HttpOnly
                Pragma: no-cache
                X-Frame-Options: SAMEORIGIN
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Content-Type-Options: nosniff
                X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-XSS-Protection: 1; mode=block
                Date: Thu, 16 Nov 2023 04:46:02 GMT
                Content-Type: application/json;charset=utf-8
                Transfer-Encoding: chunked
                Server:
        Body:
             {
                 "ERSResponse": {
                     "operation": "GET-get by name-networkdevice",
                     "messages": [
                         {
                             "title": "Error while fetching Networkdevice jeff-test2",
                             "type": "ERROR",
                             "code": "Resource not found exception"
                         }
                     ],
                     "link": {
                         "rel": "related",
                         "href": "https://10.36.126.153:9060/ers/config/networkdevice/name/jeff-test2",
                         "type": "application/xml"
                     }
                 }
             }
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ciscoisesdk/models/validators/v3_2_beta/jsd_ca6ab8ec556c3bc9531dc380b230a.py", line 234, in validate
    self._validator(request)
  File "<string>", line 56, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data.NetworkDevice.NetworkDeviceIPList[0].mask must be integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 233, in exec
    response = func(**params)
  File "/usr/local/lib/python3.9/site-packages/ciscoisesdk/api/v3_2_beta/network_device.py", line 1399, in create_network_device
    self._request_validator('jsd_ca6ab8ec556c3bc9531dc380b230a_v3_2_beta')\
  File "/usr/local/lib/python3.9/site-packages/ciscoisesdk/models/validators/v3_2_beta/jsd_ca6ab8ec556c3bc9531dc380b230a.py", line 236, in validate
    raise MalformedRequest(
ciscoisesdk.exceptions.MalformedRequest: {'NetworkDevice': {'name': 'jeff-test2', 'authenticationSettings': {'networkProtocol': 'TACACS_PLUS'}, 'tacacsSettings': {'sharedSecret': 'abcdef'}, 'NetworkDeviceIPList': [{'ipaddress': '1.1.1.2', 'mask': '30'}], 'NetworkDeviceGroupList': ['ABC123']}} is invalid. Reason: data.NetworkDevice.NetworkDeviceIPList[0].mask must be integer
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "An error occured when executing operation. The error was: {'NetworkDevice': {'name': 'jeff-test2', 'authenticationSettings': {'networkProtocol': 'TACACS_PLUS'}, 'tacacsSettings': {'sharedSecret': 'abcdef'}, 'NetworkDeviceIPList': [{'ipaddress': '1.1.1.2', 'mask': '30'}], 'NetworkDeviceGroupList': ['ABC123']}} is invalid. Reason: data.NetworkDevice.NetworkDeviceIPList[0].mask must be integer"
}
```

**Environment (please complete the following information):**
* ISE version and patch: 
* Ansible version: 
* ISE collection version:
* OS version: 

**Additional context**

For more information why `| int` filter in ansible doesn't actually convert it to a integer. https://github.com/ansible/ansible/issues/30366#issuecomment-329576139

Please allow for mask to be a string in the module arguments, and force it to an integer in the module logic before calling the SDK. Would save the headache of this workaround.
