### ISSUE TITLE
Module cisco.ise.node_replication_status_info, AttributeError: no attribute 'replication_status'

### ISSUE THREAD

**Issue by jifox** [CiscoISE/ansible-ise#127]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [x ] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

When I try to use the module 

```
- name: Read all Replication-Status of ISE Nodes
    cisco.ise.node_replication_status_info:
      ise_hostname: "{{ cisco_ise_ers_hostname }}"
      ise_username: "{{ cisco_ise_ers_username }}"
      ise_password: "{{ cisco_ise_ers_password }}"
      ise_verify: "{{ cisco_ise_ers_validate_certs }}"
      ise_uses_api_gateway: "{{ cisco_ise_ers_uses_api_gateway }}"
      ise_version: "{{ cisco_ise_version }}"
      node: "{{ item }}"
    register: res_sgts
    delegate_to: localhost
    loop: "{{ cisco_ise_hosts|list }}"
```

I've tried both, `ise_uses_api_gateway` set to `true` and `false`

```
        An error occured when retrieving operation. The error was: 'IdentityServicesEngineAPI' object has no attribute 'replication_status'
        Traceback (most recent call last):
          File "/home/ansible/dev/develop/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 221, in exec
            family = getattr(self.api, family)
        AttributeError: 'IdentityServicesEngineAPI' object has no attribute 'replication_status'
```

**Expected behavior**

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* ISE version and patch: 3.2.0.542 Patch 3
* Ansible version: $ ansible [core 2.15.10],   jinja version = 3.1.3,   libyaml = True
* ISE collection version:  2.8.1
* OS version: Ubuntu 22.04.3 LTS

**Additional context**

```bash
$ pip list | grep ciscoisesdk
ciscoisesdk               2.1.2


# /home/ansible/dev/develop/collections/ansible_collections
Collection                    Version
----------------------------- -------
ansible.netcommon             3.1.3  
ansible.utils                 2.12.0 
check_point.mgmt              4.0.0  
cisco.ise                     2.8.1  
community.general             5.8.10 
jifox.delinea_secrets_reader  1.0.0  
networktocode.nautobot        4.5.0  

```
