### ISSUE TITLE
System certificate isn't updated if the admin, portal, or SAML roles are added

### ISSUE THREAD

**Issue by mac-myers** [CiscoISE/ansible-ise#138]
**Prerequisites**
* [ X] Have you tested the operation in the API directly?
* [ X] Do you have the latest ISE Collection version?
* [ X] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Name of the module**
`cisco.ise.system_certificate`

**Describe the bug**
I had a certificate on my ISE node which only had the RADIUS role on it.

I tried using the module to update the certificate to have both the RADIUS and ADMIN roles.

The module kept saying "object already present" and wouldn't update it

**Expected behavior**
I would expect for the module to add the admin role. 

**Screenshots**
![Screenshot 2024-08-08 at 4 48 20 PM](https://github.com/user-attachments/assets/c05f0706-4d37-48b7-8922-2888d27c7856)

**Debug**

```
TASK [Update system certificate - wireless-smnt] ****************************************************************************************************************************************************************************************
task path: /...../tasks/import_system_certificate.yml:83
ok: [deployment] => changed=false 
  ise_response:
    eap: false
    expirationDate: Wed Jul 23 13:42:05 UTC 2025
    friendlyName: x
    groupTag: ''
    id: x
    ims: false
    issuedBy: x
    issuedTo: x
    keySize: 2048
    link:
      href: https://x/api/v1/certs/system-certificate/x/x
      rel: self
      type: application/json
    portalsUsingTheTag: ''
    pxgrid: false
    radius: true
    selfSigned: false
    serialNumberDecimalFormat: 'x'
    sha256Fingerprint: x
    signatureAlgorithm: x
    usedBy: RADIUS DTLS
    validFrom: Wed Jul 24 13:42:05 UTC 2024
  result: Object already present
```

**Environment (please complete the following information):**
ISE version and patch: 3.2.0.542 patch 4, 5
Ansible version: ansible [core 2.15.5] python version = 3.11.5
ISE collection version: cisco.ise 2.5.16
OS version: macOS Sonoma 14.5

**Additional context**

For some reason the module is not currently comparing these roles: 

https://github.com/CiscoISE/ansible-ise/blob/800568b4e1b8c16f090d6c9ce45203e535eb2f67/plugins/action/system_certificate.py#L146-L156
