### ISSUE TITLE
inventory variables 

### ISSUE THREAD

**Issue by oliverl-21** [CiscoISE/ansible-ise#2]
instead of using the mentioned credential.yml file u can define the variables in your inventory. this allows to reuse the playbooks for multiple deployments and only change the inventory entry.

```yml
# invetory file
[ise]
ise-beta ansible_host=198.18.168.249 ansible_user=admin ansible_password=1234QWer ise_version=3.1.0 ise_verify=false
```

in your playbook you can reference it like this

```yml
# playbook
- hosts: ise
  gather_facts: no
  tasks:
  - name: get pol set
    cisco.ise.network_access_authentication_rules_info:
      ise_hostname: "{{  ansible_host  }}"
      ise_username: "{{  ansible_user  }}"
      ise_password: "{{  ansible_password  }}"
      ise_verify: "{{  ise_verify  }}"
```
