### ISSUE TITLE
Unable to delete out-of-the-box authorization rules from Default network access policy.

### ISSUE THREAD

**Issue by bootsmo** [CiscoISE/ansible-ise#29]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?  No.
* [X] Do you have the latest ISE Collection version? yes.

**Describe the bug**
Receiving AttributeError during runtime while trying to delete authorization rules from default network access policy set.
```
[output omitted]
  File "/root/.ansible/collections/ansible_collections/cisco/ise/plugins/action/network_access_authorization_rules.py", line 244, in run
    (obj_exists, prev_obj) = obj.exists()
  File "/root/.ansible/collections/ansible_collections/cisco/ise/plugins/action/network_access_authorization_rules.py", line 109, in exists
    name = self.new_object.get('rule', {}).get("name")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Expected behavior**
Expect to delete the default authorization rules that are in the default network access policy set.

**Screenshots**

**Environment (please complete the following information):**
* ISE version and patch:  3.1, patch 1, hotfix CSCwa47133
* Ansible version: 
```
# ansible --version
ansible 2.9.6
  config file = /opt/app/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
# 
```
* ISE collection version:
```
# pip list | grep ciscoisesdk
ciscoisesdk         2.0.1               
# ansible-galaxy collection install cisco.ise:2.3.0
Process install dependency map
Starting collection install process
Skipping 'cisco.ise' as it is already installed
# 
```
* OS version: Ubuntu:focal container.  
```# uname -a
Linux cbf9639f6d65 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
This is reproducable on a default build of ISE 3.1.1.  Deployment is a VM in vSphere, built using Terraform and ISE ZTP to build VM, install patch 1, hotfix CSCwa47133, and perform initial config.  ISE node is still configured as a standalone server.
Playbook file to reproduce is attached (repro.yml.txt).
[IssueConsoleOutput.txt](https://github.com/CiscoISE/ansible-ise/files/8507663/IssueConsoleOutput.txt)
[repro.yml.txt](https://github.com/CiscoISE/ansible-ise/files/8507664/repro.yml.txt)

Intention is to remove default config (authZ policy rules, security group usage, SGTs) prior to build of desired end-state.

**Comment by bvargasre** [comment]
Hey @bootsmo, we are working on it.

**Comment by bvargasre** [comment]
Hey @bootsmo, cisco.ise:2.3.1 has been published, try the request with this version again and let us know if is working for you.

**Comment by bootsmo** [comment]
I rebuilt container and ensured v2.3.1 was used.  I am no longer getting the error messages at run time, however the delete process is not occurring.  I am testing with the same repro.yml as previously submitted.  Debug output shows the result of the delete call is "Object already absent". Console output results attached (IssueResults-v2.3.1.txt).
[IssueResults-v2.3.1.txt](https://github.com/CiscoISE/ansible-ise/files/8517497/IssueResults-v2.3.1.txt)

**Comment by bvargasre** [comment]
Hi @bootsmo, I think I know what the error may be
I have seen your playbook and found the following that you are setiing wrongly
```
    - name: Delete Default policy set authorization rules.
      cisco.ise.network_access_authorization_rules:
        <<: *ise_login
        state: absent
        id: item.rule.id
        policyId: "{{ defaultset_id }}"
      loop: "{{ defaultset_rules_table.ise_response }}"
```
The id was being equals with the "item.rule.id" and not with the value of the item.rule.id
```
    - name: Delete Default policy set authorization rules.
      cisco.ise.network_access_authorization_rules:
        <<: *ise_login
        state: absent
        id:  "{{ item.rule.id }}"
        policyId: "{{ defaultset_id }}"
      loop: "{{ defaultset_rules_table.ise_response }}"
```
