### ISSUE TITLE
netword_device authenticationSettings parameters

### ISSUE THREAD

**Issue by oliverl-21** [CiscoISE/ansible-ise#39]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?

**Describe the bug**
Network Device AuthenticationSettings are misleading, according to the documentation Authentication Setting should look like this:

      authenticationSettings:
        dtlsRequired: false
        enableKeyWrap: false
        enableMultiSecret: false
        enabled: true
        keyInputFormat: "ASCII"
        radiusSharedSecret: "key"
        networkProtocol: "RADIUS"

but ```enableMultiSecret``` errors "must be a string" and ```enabled: true``` isn't even required and also throws error if parameter is set.

```{"changed": false, "msg": "An error occured when executing operation. The error was: [400] - Resource Initialization Failed: Invalid JSON: Unrecognized field \"enabled\" (Class network.AuthenticationSettings), not marked as ignorable\n \n{\n  \"ERSResponse\" : {\n    \"operation\" : \"PUT-update by name-networkdevice\",\n    \"messages\" : [ {\n      \"title\" : \"Resource Initialization Failed: Invalid JSON: Unrecognized field \\\"enabled\\\" (Class network.AuthenticationSettings), not marked as ignorable\\n \",\n      \"type\" : \"ERROR\",\n      \"code\" : \"Application resource validation exception\"\n    } ],\n    \"link\" : {\n      \"rel\" : \"related\",\n      \"href\" : \"https://node:9060/ers/config/networkdevice/name/device\",\n      \"type\" : \"application/xml\"\n    }\n  }\n}"}```

**Expected behavior**
```enableMultiSecret``` should be a bool
```enabled``` should be marked as not required if this is intended

**Environment (please complete the following information):**
* ISE version and patch: 3.1.3
* Ansible version: core 2.11.9
* ISE collection version: 2.4.1
* OS version: SLES 15.3

**Comment by bvargasre** [comment]
Hi @oliverl-21 , reviewing the api documentation it is correct that `enableMultiSecret` is boolean and that `enable` is required. but reviewing further I saw that `enableMultiSecret` is really a string passing as a bool, this because `enableMultiSecret` supports sending bool `true/false` and string `"true"/"false"`, and in the get response of `/networkdevice/name/{name}` it shows that it is indeed a string passing as a bool.

``` json
{
    "NetworkDevice": {
        "id": "d6bd2480-dd1e-11ec-b82e-ea3fd01fddd5",
        "name": "ISE_EST_Local_Host_5",
        "description": "",
        "authenticationSettings": {
            "networkProtocol": "RADIUS",
            "radiusSharedSecret": "C1sco12345",
            "enableKeyWrap": false,
            "dtlsRequired": false,
            "keyInputFormat": "ASCII",
            "enableMultiSecret": "true", 
            "secondRadiusSharedSecret": "test"
        },
    }
}
```


The two variables are problems in the API documentation.
And as for the ansible solution, it works fine.

Playbook used for testing:
``` yaml
 - name: Create or update a network device
      cisco.ise.network_device:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: ISE_EST_Local_Host_5
        NetworkDeviceIPList:
          - ipaddress: 127.16.0.1
            mask: 32
        authenticationSettings:
          dtlsRequired: false
          enableKeyWrap: false
          enableMultiSecret: "true"
          keyInputFormat: "ASCII"
          radiusSharedSecret: "C1sco12345"
          secondRadiusSharedSecret: "test"
          networkProtocol: "RADIUS"
      register: result
```
