### ISSUE TITLE
Profiler probe config incorrectly uses GET verb instead of PUT

### ISSUE THREAD

**Issue by bootsmo** [CiscoISE/ansible-ise#63]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest ISE Collection version?

**Describe the bug**
Module cisco.ise.node_services_profiler_probe_config issues request with a GET verb instead of PUT verb.
This results in ISE only returning current configuration without any change in configuration.

**Expected behavior**
Issue request with PUT verb and configuration attribute data in body of request.

**Screenshots**
Text file with Ansible and Postman output attached here.
[ProfilerProbeConfigOutputData.txt](https://github.com/CiscoISE/ansible-ise/files/9816471/ProfilerProbeConfigOutputData.txt)

**Environment (please complete the following information):**
* ISE version and patch: 3.1 patch 1
* Ansible version: 2.10.8
* ISE collection version: 2.5.6
* OS version: Ubuntu Jammy container.

**Additional context**

**Comment by bvargasre** [comment]
Hi @bootsmo
Could you please send me the playbook you used for the tests

**Comment by bootsmo** [comment]
[profiler-config.yml.txt](https://github.com/CiscoISE/ansible-ise/files/9824932/profiler-config.yml.txt)
[profiler-services.yml.txt](https://github.com/CiscoISE/ansible-ise/files/9824933/profiler-services.yml.txt)
Attached as .txt files.
profiler-config.yml is the playbook, and profiler-services.yml is the dictionary specifying the intended service parameters.

**Comment by bvargasre** [comment]
@bootsmo I think the problem may be here `profiler-services.yml` with this `-`
``` yaml
---
profiler_config:
  # - netflow:
  - dhcp:
      interface: 'GigabitEthernet0'
      port: 67
  # - dhcpSpan:
  # - http:
  - radius: {}
  - nmap: {}
  # - dns:
  - snmpQuery:
      retries: 2
      timeout: 1000
      eventTimeout: 30
  # - snmpTrap:
  - activeDirectory:
      daysBeforeRescan: 1
  # - pxgrid: {}
  ```
  Try this change
  ``` yaml
  ---
profiler_config:
  #  netflow:
   dhcp:
      interface: 'GigabitEthernet0'
      port: 67
  #  dhcpSpan:
  #  http:
   radius: {}
   nmap: {}
  #  dns:
   snmpQuery:
      retries: 2
      timeout: 1000
      eventTimeout: 30
  #  snmpTrap:
   activeDirectory:
      daysBeforeRescan: 1
  #  pxgrid: {}
  ```
  if the problem persists, let me know

**Comment by bootsmo** [comment]
After making the suggested changes I did have to change the radius: attribute from dict to list, but otherwise I'm still getting the same results.

**Comment by bvargasre** [comment]
From the tests I have done the only thing I found was the `-` in the first level variables when I corrected it I did not find anything else and the module worked fine for me.

Add this debug
``` yaml
register: result

- name: Debug result.
  ansible.builtin.debug:
    var: result 
```
Before performing the PUT, the module performs a GET to compare bodies and verify if it needs changes, in case it does not detect changes, it sends this message "Object already present", in case there are changes, the module performs the PUT with the message "Object updated".

So if you can do one test where there are no changes and one with changes
And let me know how the tests went
``` yaml
# Configure intended services on the Profiler nodes.
- name: Update Profiler services configuration on nodes.
  cisco.ise.node_services_profiler_probe_config:
    <<: *ise_login
    state: present
    hostname: "{{ item }}"
    <<: *profiler_config
  loop: "{{ deployed_profiler }}"
  register: result

- name: Debug result.
  ansible.builtin.debug:
    var: result 
```

**Comment by bootsmo** [comment]
[ProfilerServicesTshootData20221020.txt](https://github.com/CiscoISE/ansible-ise/files/9834453/ProfilerServicesTshootData20221020.txt)
Console output attached here along with current state of playbook and input file.  Single run, two nodes.  The PAN node is preconfigured with no profiler probes enabled.  The PSN/RADIUS node is configured as intended and described in the input file.

**Comment by bvargasre** [comment]
Hi @bootsmo, ansible-ise v2.5.7 is up
Try with this new version and let me know if works for you
##
One thing I noticed is that the body of dhcp is wrong,
``` yaml
  dhcp:
    interface: 'GigabitEthernet0'
    port: 67
```
it works if it is a list of strings, but it is not, it is a list of interfaces.
``` yaml 
  dhcp:
    interfaces:
      - interface: GigabitEthernet0
    port: 67
```

**Comment by bootsmo** [comment]
We're getting closer.  Console output with debug attached.
My PAN node is not configured, which should be corrected by the playbook, and the PSN node is configured as desired so the playbook should do nothing.
The logic appears to be backwards at the moment as the playbook did not take action on the PAN node but did try to correct the PSN node.  The request sent to the PSN didn't appear to contain any data in the body.
I did correct my dictionary file as advised, current content shown in attachment.
[ProfilerServicesTshootData20221026.txt](https://github.com/CiscoISE/ansible-ise/files/9872395/ProfilerServicesTshootData20221026.txt)

**Comment by bvargasre** [comment]
In the test you did, did you remove the `-` at the first level that I told you in profiler_config?
I see in the ProfilerServicesTshootData20221026.txt that you didn't remove them, then to confirm

**Comment by bootsmo** [comment]
@bvargasre - I thought I had removed the ```-``` but that must have been in a different branch.
I also had to correct the interface name used for DHCP to include a space between the interface type and the numeral.
Testing is now showing desired results.  OK to close issue.

If it helps anyone else, here's my playbook followed by the data being used by the playbook:
```
---
- name: Configure profiling services for all enabled profiling nodes.
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars/common/vars.yml
    - ../BuildData/profiler-services.yml

  vars:
    ise_login: &ise_login
      ise_hostname: "{{ ise_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      ise_debug: "{{ ise_debug }}"
      ise_uses_api_gateway: "{{ ise_uses_api_gateway }}"
      ise_version: "{{ ise_version }}"

    profiler_config: &profiler_config
      activeDirectory: "{{ profiler_config.activeDirectory | default(omit) }}"
      dhcp: "{{ profiler_config.dhcp | default(omit) }}"
      dhcpSpan: "{{ profiler_config.dhcpSpan | default(omit) }}"
      dns: "{{ profiler_config.dns | default(omit) }}"
      http: "{{ profiler_config.http | default(omit) }}"
      netflow: "{{ profiler_config.netflow | default(omit) }}"
      nmap: "{{ profiler_config.nmap | default(omit) }}"
      pxgrid: "{{ profiler_config.pxgrid | default(omit) }}"
      radius: "{{ profiler_config.radius | default(omit) }}"
      snmpQuery: "{{ profiler_config.snmpQuery | default(omit) }}"
      snmpTrap: "{{ profiler_config.snpTrap | default(omit) }}"

  # NOTE: pxGrid profiler cannot be enabled without pxGrid node in deployment.

  tasks:

    # Get list of Profiler nodes in environment.
    - name: Get list of nodes currently in environment.
      block:
      - name: Get all Node Deployment
        cisco.ise.node_deployment_info:
          <<: *ise_login
          filter: []
          filterType: "AND"
        register: node_data

      - name: Initialize deployed_profiler list.
        set_fact:
          deployed_profiler: []

      - name: Populate deployed_profiler list.
        set_fact:
          deployed_profiler: "{{ deployed_profiler + [ item.hostname ] }}"
        when: '"Profiler" in item.services'
        loop: "{{ node_data.ise_response }}"

    # Configure intended services on the Profiler nodes.
    - name: Update Profiler services configuration on nodes.
      cisco.ise.node_services_profiler_probe_config:
        <<: *ise_login
        state: present
        hostname: "{{ item }}"
        <<: *profiler_config
      loop: "{{ deployed_profiler }}"
```

```
---
profiler_config:
  # netflow:
  dhcp:
    interfaces:
      - interface: 'GigabitEthernet 0'
    port: 67
  # dhcpSpan:
  # http:
  radius: []
  nmap: []
  # dns:
  snmpQuery:
    retries: 2
    timeout: 1000
    eventTimeout: 30
  # snmpTrap:
  activeDirectory:
    daysBeforeRescan: 1
  # pxgrid: {}
```
