### ISSUE TITLE
System Certificate Update does not work but always reports Object already present

### ISSUE THREAD

**Issue by chetanph** [CiscoISE/ansible-ise#91]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

[System Certificate Update](https://docs.ansible.com/ansible/latest/collections/cisco/ise/system_certificate_module.html#ansible-collections-cisco-ise-system-certificate-module) does not function as expected. The module just performs a GET request and then does not perform a PUT request as needed.

**Expected behavior**

The module should correctly detect that there are changes requested in the certificate and perform a PUT request.

**Screenshots**

![Screenshot 2023-07-10 at 5 06 06 PM](https://github.com/CiscoISE/ansible-ise/assets/29963552/37deb6f5-2690-4fbf-9e36-50e87cf9f989)

**Environment (please complete the following information):**
* ISE version and patch: ISE Version 3.1 patch 6
* Ansible version: 2.14.6
* ISE collection version: cisco.ise 2.5.12
* OS version: macOS Ventura 13.4.1

**Additional context**

Here's the test playbook:

```yaml
---
- name: Test
  hosts: "localhost"
  vars:
    ise_hostname: 10.11.12.13
    ise_username: api-access
    ise_password: Examp1ePassw0rd!*
  gather_facts: false
  tasks:
    - name: Get System Certificate by name
      cisco.ise.system_certificate_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        ise_debug: true
        page: 1
        size: 10
        hostName: mapper01.cisco.com
        filter:
          - friendlyName.EQ.System_Cert_for_Ansible_Test
      register: cert_info

    - name: Update by id
      cisco.ise.system_certificate:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        ise_debug: true
        state: present
        admin: false
        allowPortalTagTransferForSameSubject: true
        allowReplacementOfPortalGroupTag: true
        allowRoleTransferForSameSubject: true
        description: Updated system certificate.
        hostName: mapper01.cisco.com
        id: "{{ cert_info.ise_response[0].id }}"
        ims: false
        name: System_Cert_for_Ansible_Test
        pxgrid: false
        radius: false
        eap: true
```

Here's the output:

```
TASK [Get System Certificate by name] ****************************************************************************************************
task path: /Users/cphulpag/Documents/SOAR/Code/ise-infra-as-code/ansible/system_certificate_update.yml:10
Attempt 1

Request
    URL: https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com
    Method: GET
    Headers:
        User-Agent: python-requests/2.31.0
        Accept-Encoding: gzip, deflate
        Accept: application/json
        Connection: keep-alive
        authorization: Basic XXXXXXXX
        Content-type: application/json;charset=utf-8
    Params:
              {
                  "page": 1,
                  "size": 10,
                  "filter": [
                      "friendlyName.EQ.System_Cert_for_Ansible_Test"
                  ]
              }

Response
    Status: 200 -
    Headers:
        Content-Type: application/json
        Transfer-Encoding: chunked
        Connection: keep-alive
        Cache-Control: no-cache, no-store, must-revalidate
        Expires: Thu, 01 Jan 1970 00:00:00 GMT
        Set-Cookie: JSESSIONIDSSO=E353FBEE05884755B70F3F9870D2D91E; Path=/; Secure; HttpOnly, APPSESSIONID=6D772C04BD2361A8F7A404BFAA58D0C0; Path=/api; Secure; HttpOnly
        Pragma: no-cache
        X-Request-ID: 6ed38290-1f64-11ee-b492-22f55c3cd0d4
        X-Frame-Options: SAMEORIGIN
        Strict-Transport-Security: max-age=31536000; includeSubDomains
        X-Content-Type-Options: nosniff
        X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
        X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
        Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
        X-XSS-Protection: 1; mode=block
        Content-Disposition: inline;filename=f.txt
        vary: accept-encoding
        Content-Encoding: gzip
        Date: Mon, 10 Jul 2023 20:57:51 GMT
        Server:
    Body:
             {
                 "response": [
                     {
                         "id": "d4f7aa21-cf97-456c-8f00-bbf7b062385e",
                         "friendlyName": "System_Cert_for_Ansible_Test",
                         "serialNumberDecimalFormat": "168840527315026912937992232939",
                         "issuedTo": "mapper01.cisco.com",
                         "issuedBy": "mapper01.cisco.com",
                         "validFrom": "Mon Jul 03 13:27:53 EDT 2023",
                         "expirationDate": "Wed Jul 02 13:27:53 EDT 2025",
                         "usedBy": "pxGrid, RADIUS DTLS, EAP Authentication",
                         "keySize": 4096,
                         "groupTag": "",
                         "selfSigned": true,
                         "signatureAlgorithm": "SHA384withRSA",
                         "portalsUsingTheTag": "",
                         "sha256Fingerprint": "2041a79718dd015c7bc93d19a88f116da06bf250cfc42948202706d6d482363d",
                         "link": {
                             "rel": "self",
                             "href": "https://10.11.12.13/api/v1/certs/system-certificate/mapper01/d4f7aa21-cf97-456c-8f00-bbf7b062385e",
                             "type": "application/json"
                         }
                     }
                 ],
                 "nextPage": null,
                 "previousPage": null,
                 "version": "1.0.1"
             }
ok: [localhost] => changed=false
  ise_response:
  - expirationDate: Wed Jul 02 13:27:53 EDT 2025
    friendlyName: System_Cert_for_Ansible_Test
    groupTag: ''
    id: d4f7aa21-cf97-456c-8f00-bbf7b062385e
    issuedBy: mapper01.cisco.com
    issuedTo: mapper01.cisco.com
    keySize: 4096
    link:
      href: https://10.11.12.13/api/v1/certs/system-certificate/mapper01/d4f7aa21-cf97-456c-8f00-bbf7b062385e
      rel: self
      type: application/json
    portalsUsingTheTag: ''
    selfSigned: true
    serialNumberDecimalFormat: '168840527315026912937992232939'
    sha256Fingerprint: 2041a79718dd015c7bc93d19a88f116da06bf250cfc42948202706d6d482363d
    signatureAlgorithm: SHA384withRSA
    usedBy: pxGrid, RADIUS DTLS, EAP Authentication
    validFrom: Mon Jul 03 13:27:53 EDT 2023
  result: ''

TASK [Update by id] **********************************************************************************************************************
task path: /Users/cphulpag/Documents/SOAR/Code/ise-infra-as-code/ansible/system_certificate_update.yml:24
Attempt 1

Request
    URL: https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com/d4f7aa21-cf97-456c-8f00-bbf7b062385e
    Method: GET
    Headers:
        User-Agent: python-requests/2.31.0
        Accept-Encoding: gzip, deflate
        Accept: application/json
        Connection: keep-alive
        authorization: Basic XXXXXXXX
        Content-type: application/json;charset=utf-8
    Params:
              {}

Response
    Status: 200 -
    Headers:
        Content-Type: application/json
        Transfer-Encoding: chunked
        Connection: keep-alive
        Cache-Control: no-cache, no-store, must-revalidate
        Expires: Thu, 01 Jan 1970 00:00:00 GMT
        Set-Cookie: JSESSIONIDSSO=C0AE7ECE2CE4156A6811E427B0180955; Path=/; Secure; HttpOnly, APPSESSIONID=D965EFE530DEA52A807B99685A242461; Path=/api; Secure; HttpOnly
        Pragma: no-cache
        X-Request-ID: 6f430d40-1f64-11ee-b492-22f55c3cd0d4
        X-Frame-Options: SAMEORIGIN
        Strict-Transport-Security: max-age=31536000; includeSubDomains
        X-Content-Type-Options: nosniff
        X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
        X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
        Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
        X-XSS-Protection: 1; mode=block
        vary: accept-encoding
        Content-Encoding: gzip
        Date: Mon, 10 Jul 2023 20:57:51 GMT
        Server:
    Body:
             {
                 "response": {
                     "id": "d4f7aa21-cf97-456c-8f00-bbf7b062385e",
                     "friendlyName": "System_Cert_for_Ansible_Test",
                     "serialNumberDecimalFormat": "168840527315026912937992232939",
                     "issuedTo": "mapper01.cisco.com",
                     "issuedBy": "mapper01.cisco.com",
                     "validFrom": "Mon Jul 03 13:27:53 EDT 2023",
                     "expirationDate": "Wed Jul 02 13:27:53 EDT 2025",
                     "usedBy": "pxGrid, RADIUS DTLS, EAP Authentication",
                     "keySize": 4096,
                     "groupTag": "",
                     "selfSigned": true,
                     "signatureAlgorithm": "SHA384withRSA",
                     "portalsUsingTheTag": "",
                     "sha256Fingerprint": "2041a79718dd015c7bc93d19a88f116da06bf250cfc42948202706d6d482363d",
                     "link": {
                         "rel": "self",
                         "href": "https://10.11.12.13/api/v1/certs/system-certificate/mapper01/d4f7aa21-cf97-456c-8f00-bbf7b062385e",
                         "type": "application/json"
                     }
                 },
                 "version": "1.0.1"
             }
ok: [localhost] => changed=false
  ise_response:
    response:
      expirationDate: Wed Jul 02 13:27:53 EDT 2025
      friendlyName: System_Cert_for_Ansible_Test
      groupTag: ''
      id: d4f7aa21-cf97-456c-8f00-bbf7b062385e
      issuedBy: mapper01.cisco.com
      issuedTo: mapper01.cisco.com
      keySize: 4096
      link:
        href: https://10.11.12.13/api/v1/certs/system-certificate/mapper01/d4f7aa21-cf97-456c-8f00-bbf7b062385e
        rel: self
        type: application/json
      portalsUsingTheTag: ''
      selfSigned: true
      serialNumberDecimalFormat: '168840527315026912937992232939'
      sha256Fingerprint: 2041a79718dd015c7bc93d19a88f116da06bf250cfc42948202706d6d482363d
      signatureAlgorithm: SHA384withRSA
      usedBy: pxGrid, RADIUS DTLS, EAP Authentication
      validFrom: Mon Jul 03 13:27:53 EDT 2023
    version: 1.0.1
  result: Object already present

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

The Ansible module is not able to detect that there is a change required for the system certificate in the roles assigned to the certificate.

This [function](https://github.com/CiscoISE/ansible-ise/blob/edb3f312f7b510796e328586c5a5a2c0020a0cbf/plugins/action/system_certificate.py#L143C9-L143C24) in the module is trying to compare fields from GET response that the response doesn't contain. For some reason, the schema for GET response for system certificate and schema of PUT request for system certificate are different, e.g. GET response contains `friendlyName` field which is referred to as `name` in PUT request. GET response just contains single `usedBy` field instead of individual `eap`, `radius`, `admin` fields used in PUT request.
