### ISSUE TITLE
System Certificate Delete does not work at all

### ISSUE THREAD

**Issue by chetanph** [CiscoISE/ansible-ise#92]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**

System Certificate Delete API is not working, it always returns a HTTP 422 error. Deleting same
certificate from the GUI works fine.

**Expected behavior**

When the system certificate is not in use, the API request and in turn the module should succeed in 
deleting the system certificate. In short, API should exhibit same behavior as the GUI.

**Screenshots**

Screenshot of the certificate from the GUI:

<img width="1118" alt="Screenshot 2023-07-11 at 11 43 45 AM" src="https://github.com/CiscoISE/ansible-ise/assets/29963552/efef37fe-5b25-47ee-b30e-8535c168702d">

Here's the `curl` output of direct API call that fails with HTTP 422.

```
curl --insecure -vvv -X DELETE -u 'api-access:Examp1ePassw0rd!*' https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com/dbc54911-996f-4152-9fa1-ae01c27505d2
*   Trying 10.11.12.13:443...
* Connected to 10.11.12.13 (10.11.12.13) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=mapper01.cisco.com; OU=Security Orchestration; O=Customer Experience; L=Sano Jose; ST=California; C=US
*  start date: May 25 20:02:17 2023 GMT
*  expire date: May 22 20:02:17 2033 GMT
*  issuer: C=US; ST=California; L=San Jose; O=Customer Experience; OU=Security Orchestration; CN=soar-intermediate.cisco.com; emailAddress=securityorchestration@cisco.com
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* using HTTP/1.1
* Server auth using Basic with user 'api-access'
> DELETE /api/v1/certs/system-certificate/mapper01.cisco.com/dbc54911-996f-4152-9fa1-ae01c27505d2 HTTP/1.1
> Host: 10.11.12.13
> Authorization: Basic XXXXXXXX
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 422 
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache, no-store, must-revalidate
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: JSESSIONIDSSO=0BF3155AAEFBC57BF6B0F24D53415B23; Path=/; Secure; HttpOnly
< Set-Cookie: APPSESSIONID=8BCAB6AFE64175AD9B923DED517B73BB; Path=/api; Secure; HttpOnly
< Pragma: no-cache
< X-Request-ID: 89eb9c40-200c-11ee-b492-22f55c3cd0d4
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
< X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
< X-XSS-Protection: 1; mode=block
< vary: accept-encoding
< Date: Tue, 11 Jul 2023 17:01:12 GMT
< Server: 
< 
{
  "response" : {
    "message" : null
  },
  "version" : "1.0.1"
}%  
```

**Environment (please complete the following information):**

* ISE version and patch: ISE Version 3.2.0.542 patch 1
* Ansible version: 2.14.6
* ISE collection version: cisco.ise 2.5.12
* OS version: macOS Ventura 13.4.1

**Additional context**

Playbook:

```yml
---
- name: Test
  hosts: "localhost"
  vars:
    ise_hostname: 10.11.12.13
    ise_username: api-access
    ise_password: Examp1ePassw0rd!*
    ise_ppan_fqdn: mapper01.cisco.com
  gather_facts: false
  tasks:
    - name: Get System Certificate by name
      cisco.ise.system_certificate_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        ise_debug: true
        page: 1
        size: 10
        hostName: "{{ ise_ppan_fqdn }}"
        filter:
          - friendlyName.EQ.Test_Cert_for_Deletion
      register: cert_info

    - name: Is the certificate in use?
      ansible.builtin.debug:
        msg: Certificate is not in use
      when: cert_info.ise_response[0].usedBy == 'Not in use'

    - name: Create curl command to delete manually
      ansible.builtin.debug:
        msg: "curl --insecure -vvv -X DELETE -u '{{ ise_username }}:{{ ise_password }}' https://{{ ise_hostname }}/api/v1/certs/system-certificate/{{ ise_ppan_fqdn }}/{{ cert_info.ise_response[0].id }}"

    - name: Delete by id
      cisco.ise.system_certificate:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        ise_debug: true
        state: absent
        hostName: "{{ ise_ppan_fqdn }}"
        id: "{{ cert_info.ise_response[0].id }}"
      when: cert_info.ise_response[0].usedBy == 'Not in use'
```

Here's the log of the playbook, clearly showing that the certificate is not in use.

```
TASK [Get System Certificate by name] ********************************************************************************************************************************************
task path: /Users/cphulpag/Documents/SOAR/Code/ise-infra-as-code/ansible/system_certificate_delete.yml:13
Attempt 1

Request
        URL: https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com
        Method: GET
        Headers: 
                User-Agent: python-requests/2.31.0
                Accept-Encoding: gzip, deflate
                Accept: application/json
                Connection: keep-alive
                authorization: Basic XXXXXXXX
                Content-type: application/json;charset=utf-8
        Params:
              {
                  "page": 1,
                  "size": 10,
                  "filter": [
                      "friendlyName.EQ.Test_Cert_for_Deletion"
                  ]
              }

Response
        Status: 200 - 
        Headers: 
                Content-Type: application/json
                Transfer-Encoding: chunked
                Connection: keep-alive
                Cache-Control: no-cache, no-store, must-revalidate
                Expires: Thu, 01 Jan 1970 00:00:00 GMT
                Set-Cookie: JSESSIONIDSSO=FF3BFA541C83D5852AE90BE722C15B5F; Path=/; Secure; HttpOnly, APPSESSIONID=99641ACCB7496042712C1FC053DF580C; Path=/api; Secure; HttpOnly
                Pragma: no-cache
                X-Request-ID: 8f1a5cb0-200c-11ee-b492-22f55c3cd0d4
                X-Frame-Options: SAMEORIGIN
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Content-Type-Options: nosniff
                X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-XSS-Protection: 1; mode=block
                Content-Disposition: inline;filename=f.txt
                vary: accept-encoding
                Content-Encoding: gzip
                Date: Tue, 11 Jul 2023 17:01:20 GMT
                Server: 
        Body:
             {
                 "response": [
                     {
                         "id": "dbc54911-996f-4152-9fa1-ae01c27505d2",
                         "friendlyName": "Test_Cert_for_Deletion",
                         "serialNumberDecimalFormat": "16890853097152022413619621324",
                         "issuedTo": "mapper01.cisco.com",
                         "issuedBy": "mapper01.cisco.com",
                         "validFrom": "Tue Jul 11 10:21:49 EDT 2023",
                         "expirationDate": "Thu Jul 10 10:21:49 EDT 2025",
                         "usedBy": "Not in use",
                         "keySize": 4096,
                         "groupTag": "",
                         "selfSigned": true,
                         "signatureAlgorithm": "SHA384withRSA",
                         "portalsUsingTheTag": "",
                         "sha256Fingerprint": "9633a9a201149fbaf74413e70abc6a0a91ab8c96886a8eec4dd0a95b2388c1c3",
                         "link": {
                             "rel": "self",
                             "href": "https://10.11.12.13/api/v1/certs/system-certificate/mapper01/dbc54911-996f-4152-9fa1-ae01c27505d2",
                             "type": "application/json"
                         }
                     }
                 ],
                 "nextPage": null,
                 "previousPage": null,
                 "version": "1.0.1"
             }
ok: [localhost] => changed=false 
  ise_response:
  - expirationDate: Thu Jul 10 10:21:49 EDT 2025
    friendlyName: Test_Cert_for_Deletion
    groupTag: ''
    id: dbc54911-996f-4152-9fa1-ae01c27505d2
    issuedBy: mapper01.cisco.com
    issuedTo: mapper01.cisco.com
    keySize: 4096
    link:
      href: https://10.11.12.13/api/v1/certs/system-certificate/mapper01/dbc54911-996f-4152-9fa1-ae01c27505d2
      rel: self
      type: application/json
    portalsUsingTheTag: ''
    selfSigned: true
    serialNumberDecimalFormat: '16890853097152022413619621324'
    sha256Fingerprint: 9633a9a201149fbaf74413e70abc6a0a91ab8c96886a8eec4dd0a95b2388c1c3
    signatureAlgorithm: SHA384withRSA
    usedBy: Not in use
    validFrom: Tue Jul 11 10:21:49 EDT 2023
  result: ''

TASK [Is the certificate in use?] ************************************************************************************************************************************************
task path: /Users/cphulpag/Documents/SOAR/Code/ise-infra-as-code/ansible/system_certificate_delete.yml:27
ok: [localhost] => 
  msg: Certificate is not in use

TASK [Create curl command to delete manually] ************************************************************************************************************************************
task path: /Users/cphulpag/Documents/SOAR/Code/ise-infra-as-code/ansible/system_certificate_delete.yml:32
ok: [localhost] => 
  msg: curl --insecure -vvv -X DELETE -u 'api-access:Examp1ePassw0rd!*' https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com/dbc54911-996f-4152-9fa1-ae01c27505d2

TASK [Delete by id] **************************************************************************************************************************************************************
task path: /Users/cphulpag/Documents/SOAR/Code/ise-infra-as-code/ansible/system_certificate_delete.yml:36
Attempt 1

Request
        URL: https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com/dbc54911-996f-4152-9fa1-ae01c27505d2
        Method: GET
        Headers: 
                User-Agent: python-requests/2.31.0
                Accept-Encoding: gzip, deflate
                Accept: application/json
                Connection: keep-alive
                authorization: Basic XXXXXXXX
                Content-type: application/json;charset=utf-8
        Params:
              {}

Response
        Status: 200 - 
        Headers: 
                Content-Type: application/json
                Transfer-Encoding: chunked
                Connection: keep-alive
                Cache-Control: no-cache, no-store, must-revalidate
                Expires: Thu, 01 Jan 1970 00:00:00 GMT
                Set-Cookie: JSESSIONIDSSO=CCEF2EDC4DC4096074CBA9B073BE5231; Path=/; Secure; HttpOnly, APPSESSIONID=BD1EBE2C29A487BE0C61087F582BCF28; Path=/api; Secure; HttpOnly
                Pragma: no-cache
                X-Request-ID: 8f913a60-200c-11ee-b492-22f55c3cd0d4
                X-Frame-Options: SAMEORIGIN
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Content-Type-Options: nosniff
                X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-XSS-Protection: 1; mode=block
                vary: accept-encoding
                Content-Encoding: gzip
                Date: Tue, 11 Jul 2023 17:01:20 GMT
                Server: 
        Body:
             {
                 "response": {
                     "id": "dbc54911-996f-4152-9fa1-ae01c27505d2",
                     "friendlyName": "Test_Cert_for_Deletion",
                     "serialNumberDecimalFormat": "16890853097152022413619621324",
                     "issuedTo": "mapper01.cisco.com",
                     "issuedBy": "mapper01.cisco.com",
                     "validFrom": "Tue Jul 11 10:21:49 EDT 2023",
                     "expirationDate": "Thu Jul 10 10:21:49 EDT 2025",
                     "usedBy": "Not in use",
                     "keySize": 4096,
                     "groupTag": "",
                     "selfSigned": true,
                     "signatureAlgorithm": "SHA384withRSA",
                     "portalsUsingTheTag": "",
                     "sha256Fingerprint": "9633a9a201149fbaf74413e70abc6a0a91ab8c96886a8eec4dd0a95b2388c1c3",
                     "link": {
                         "rel": "self",
                         "href": "https://10.11.12.13/api/v1/certs/system-certificate/mapper01/dbc54911-996f-4152-9fa1-ae01c27505d2",
                         "type": "application/json"
                     }
                 },
                 "version": "1.0.1"
             }
Attempt 1

Request
        URL: https://10.11.12.13/api/v1/certs/system-certificate/mapper01.cisco.com/dbc54911-996f-4152-9fa1-ae01c27505d2
        Method: DELETE
        Headers: 
                User-Agent: python-requests/2.31.0
                Accept-Encoding: gzip, deflate
                Accept: application/json
                Connection: keep-alive
                authorization: Basic XXXXXXXX
                Content-type: application/json;charset=utf-8
        Params:
              {}

Response
        Status: 422 - 
        Headers: 
                Content-Type: application/json
                Transfer-Encoding: chunked
                Connection: keep-alive
                Cache-Control: no-cache, no-store, must-revalidate
                Expires: Thu, 01 Jan 1970 00:00:00 GMT
                Pragma: no-cache
                X-Request-ID: 8f9ea7e0-200c-11ee-b492-22f55c3cd0d4
                X-Frame-Options: SAMEORIGIN
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Content-Type-Options: nosniff
                X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-XSS-Protection: 1; mode=block
                vary: accept-encoding
                Content-Encoding: gzip
                Date: Tue, 11 Jul 2023 17:01:20 GMT
                Server: 
        Body:
             {
                 "response": {
                     "message": null
                 },
                 "version": "1.0.1"
             }
The full traceback is:
Traceback (most recent call last):
  File "/Users/cphulpag/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 231, in exec
    response = func(**params)
  File "/Users/cphulpag/Documents/SOAR/Code/ise-cube/venv/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/certificates.py", line 2574, in delete_system_certificate_by_id
    _api_response = self._session.delete(endpoint_full_url, params=_params,
  File "/Users/cphulpag/Documents/SOAR/Code/ise-cube/venv/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 702, in delete
    response = self.request('DELETE', url, erc, 0, params=params, **kwargs)
  File "/Users/cphulpag/Documents/SOAR/Code/ise-cube/venv/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/Users/cphulpag/Documents/SOAR/Code/ise-cube/venv/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [422] - Unknown Error
{
  "response" : {
    "message" : null
  },
  "version" : "1.0.1"
}
fatal: [localhost]: FAILED! => changed=false 
  msg: |-
    An error occured when executing operation. The error was: [422] - Unknown Error
    {
      "response" : {
        "message" : null
      },
      "version" : "1.0.1"
    }

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by chetanph** [comment]
This is a working idempotent example that also check if the certificate is not in use. Otherwise the API request will fail:

```yaml
---
- name: Test System Certificate Delete
  hosts: "localhost"
  vars:
    ise_hostname: 10.x.x.x
    ise_username: api-access
    ise_password: ABCD
    ise_fqdn: ise-32-ansible.cisco.com
  gather_facts: false
  tasks:
    - name: Get System Certificate by name
      cisco.ise.system_certificate_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: false
        ise_debug: true
        page: 1
        size: 10
        hostName: "{{ ise_fqdn }}"
        filter:
          - friendlyName.EQ.Test_Cert_for_Deletion
      register: cert_info

    - name: Is the certificate still there?
      when: cert_info.ise_response | length > 0
      block:
        - name: Is the certificate in use?
          ansible.builtin.debug:
            msg: Certificate is not in use
          when:
            - cert_info.ise_response[0].usedBy == 'Not in use'

        - name: Delete by id
          cisco.ise.system_certificate:
            ise_hostname: "{{ ise_hostname }}"
            ise_username: "{{ ise_username }}"
            ise_password: "{{ ise_password }}"
            ise_verify: false
            ise_debug: true
            state: absent
            hostName: "{{ ise_fqdn }}"
            id: "{{ cert_info.ise_response[0].id }}"
            allowWildcardDelete: true
          when: cert_info.ise_response[0].usedBy == 'Not in use'
```
