### ISSUE TITLE
Cannot get cisco.ise.rest_id_store to work

### ISSUE THREAD

**Issue by wastorga** [CiscoISE/ansible-ise#94]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [ ] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
 I cannot get cisco.ise.rest_id_store to work.
 
 ```yml
 - name: Create REST ID Store (AzureAD)
  delegate_to: localhost
  cisco.ise.rest_id_store:
    ise_hostname: "{{ ansible_host }}"
    ise_username: "{{ ise_username | default( omit ) }}"
    ise_password: "{{ ise_password | default( omit ) }}"
    state: present
    name: AAD_trust0
    description: AAD_trust0
    ersRestIDStoreAttributes:
      predefined: Azure
      usernameSuffix: "@trust0.onmicrosoft.com"
      rootUrl: "http://***:9601/azure"
      headers:
      - key: clientID
        value: "***"
      - key: clientSecret
        value: "***"
      - key: tenantID
        value: "***"
  register: aad_created
  ignore_errors: yes 
 ```
 
 I always get the error :
 
 ```json
 "ERSResponse" : {
          "operation" : "POST-create-restidstore",
          "messages" : [ {
            "title" : "Resource Initialization Failed(10)",
            "type" : "ERROR",
            "code" : "Application resource validation exception"
          } ] 
 ```

**Expected behavior**
That it works, since using ansible.builtin.uri module works.

**Screenshots**

```yml
- name: Create AAD_trust0 REST ID Store
  delegate_to: localhost
  ansible.builtin.uri:
    url: https://{{ ansible_host }}/ers/config/restidstore
    method: POST
    url_username: "{{ ise_username }}"
    url_password: "{{ ise_password }}"
    force_basic_auth: yes
    headers:
      Accept: application/json
      Content-Type: application/json
    body: |
      {
        "ERSRestIDStore" : {
          "name" : "AAD_trust0",
          "description" : "",
          "ersRestIDStoreAttributes" : {
            "usernameSuffix" : "@trust0.onmicrosoft.com",
            "rootUrl" : "http://****:9601/azure",
            "predefined" : "Azure",
            "headers" : [ {
              "key" : "clientID",
              "value" : "*******"
            }, {
              "key" : "clientSecret",
              "value" : "****"
            }, {
              "key" : "tenantID",
              "value" : "****"
            } ]
          },
          "ersRestIDStoreUserAttributes" : {
            "attributes" : [ ]
          }
        }
      }
    status_code: 201
    validate_certs: "{{ lookup('env','ISE_VERIFY') | default( false )}}"
    return_content: true
  register: aad_created
  ignore_errors: yes 
```

**Environment (please complete the following information):**
* ISE version and patch: 
* Ansible version: 8.1.0, ansible-core: 2.15.1
* ciscoisesdk : 2.0.9
* ISE collection version:
* OS version: 

**Additional context**
Originally reported by Thomas Howard on Webex space.
